from services.models import Source
from sqlalchemy.orm import Session

SOURCES_DATA = [
    # --- USA ---
    {
        "name": "SEC EDGAR",
        "source_type": "filings",
        "coverage": "usa",
        "data_offered": "Filings 10-K, 10-Q, 8-K, proxy, XBRL datos estructurados",
        "access_type": "web, api",
        "limitations": "Solo empresas cotizadas en USA. Full-text search puede ser lento.",
        "url": "https://www.sec.gov/cgi-bin/browse-edgar",
        "reliability": "alta",
        "notes": "Fuente primaria de filings en USA. API EDGAR disponible. Datos XBRL parseables.",
        "verified": True,
    },
    {
        "name": "FRED (Federal Reserve Economic Data)",
        "source_type": "macro",
        "coverage": "usa, global",
        "data_offered": "Tipos de interes, inflacion, empleo, PIB, indicadores monetarios, spreads",
        "access_type": "web, api",
        "limitations": "Requiere API key gratuita para uso intensivo.",
        "url": "https://fred.stlouisfed.org/",
        "reliability": "alta",
        "notes": "Referencia mundial para datos macro USA. API REST gratuita.",
        "verified": True,
    },
    {
        "name": "Yahoo Finance",
        "source_type": "precios",
        "coverage": "usa, global",
        "data_offered": "Precios historicos, fundamentales basicos, dividendos, earnings",
        "access_type": "web",
        "limitations": "Datos con 15 min retraso. Scraping en zona gris legal. Usar yfinance (no oficial).",
        "url": "https://finance.yahoo.com/",
        "reliability": "media",
        "notes": "Amplia cobertura global. Libreria yfinance facilita acceso pero no es API oficial.",
        "verified": True,
    },
    # --- EUROPA ---
    {
        "name": "ECB Statistical Data Warehouse",
        "source_type": "macro",
        "coverage": "europa, global",
        "data_offered": "Tipos de interes BCE, tipos de cambio, agregados monetarios, balanza de pagos",
        "access_type": "web, api",
        "limitations": "Interfaz compleja. Datos con retraso de publicacion.",
        "url": "https://sdw.ecb.europa.eu/",
        "reliability": "alta",
        "notes": "Fuente oficial del BCE. API SDMX disponible.",
        "verified": True,
    },
    {
        "name": "ECB Euro Foreign Exchange Rates",
        "source_type": "fx",
        "coverage": "europa, global",
        "data_offered": "Tipos de cambio del euro contra ~30 divisas, historico diario",
        "access_type": "web, descarga",
        "limitations": "Solo tipos de referencia (cierre). Una actualizacion diaria.",
        "url": "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/",
        "reliability": "alta",
        "notes": "Tipos oficiales del BCE. Descarga CSV directa.",
        "verified": True,
    },
    {
        "name": "Eurostat",
        "source_type": "macro",
        "coverage": "europa",
        "data_offered": "PIB, inflacion, empleo, comercio, demografia por pais UE",
        "access_type": "web, api",
        "limitations": "Datos con retraso. Interfaz de consulta compleja.",
        "url": "https://ec.europa.eu/eurostat",
        "reliability": "alta",
        "notes": "Oficina estadistica de la UE. API JSON disponible.",
        "verified": True,
    },
    {
        "name": "ESMA / ESEF",
        "source_type": "regulador",
        "coverage": "europa",
        "data_offered": "Regulacion de mercados, informes anuales ESEF (XBRL europeo)",
        "access_type": "web",
        "limitations": "Informacion regulatoria, no datos de mercado directos.",
        "url": "https://www.esma.europa.eu/",
        "reliability": "alta",
        "notes": "Regulador europeo de mercados. ESEF para informes anuales en formato XBRL.",
        "verified": True,
    },
    # --- ESPANA ---
    {
        "name": "CNMV",
        "source_type": "regulador",
        "coverage": "espana",
        "data_offered": "Hechos relevantes, folletos, informes anuales, participaciones significativas",
        "access_type": "web",
        "limitations": "Busqueda poco amigable. Sin API publica.",
        "url": "https://www.cnmv.es/",
        "reliability": "alta",
        "notes": "Regulador del mercado espanol. Fuente oficial para filings en Espana.",
        "verified": True,
    },
    {
        "name": "Bolsas y Mercados Espanoles (BME)",
        "source_type": "bolsa",
        "coverage": "espana",
        "data_offered": "Cotizaciones IBEX 35, datos de mercado, estadisticas, indices",
        "access_type": "web",
        "limitations": "Datos en tiempo real de pago. Datos de cierre gratuitos.",
        "url": "https://www.bolsasymercados.es/",
        "reliability": "alta",
        "notes": "Operador de bolsas en Espana. Informacion de mercado basica gratuita.",
        "verified": True,
    },
    {
        "name": "Banco de Espana",
        "source_type": "banco_central",
        "coverage": "espana",
        "data_offered": "Estadisticas bancarias, tipos de interes, balanza de pagos, estabilidad financiera",
        "access_type": "web, descarga",
        "limitations": "Foco en sector bancario y macro espanol.",
        "url": "https://www.bde.es/bde/es/areas/estadis/",
        "reliability": "alta",
        "notes": "Banco central espanol. Informes de estabilidad financiera muy utiles.",
        "verified": True,
    },
    # --- UK ---
    {
        "name": "Companies House",
        "source_type": "filings",
        "coverage": "uk",
        "data_offered": "Cuentas anuales, informacion societaria, directivos, filings",
        "access_type": "web, api",
        "limitations": "Solo empresas registradas en UK. API gratuita con registro.",
        "url": "https://www.gov.uk/government/organisations/companies-house",
        "reliability": "alta",
        "notes": "Registro mercantil de UK. API REST gratuita.",
        "verified": True,
    },
    {
        "name": "Bank of England Statistics",
        "source_type": "banco_central",
        "coverage": "uk",
        "data_offered": "Tipos de interes, inflacion, agregados monetarios, datos bancarios",
        "access_type": "web, descarga",
        "limitations": "Foco en UK.",
        "url": "https://www.bankofengland.co.uk/statistics",
        "reliability": "alta",
        "notes": "Banco central de UK. Descarga CSV de series historicas.",
        "verified": True,
    },
    {
        "name": "London Stock Exchange",
        "source_type": "bolsa",
        "coverage": "uk",
        "data_offered": "Cotizaciones, indices FTSE, datos de mercado",
        "access_type": "web",
        "limitations": "Datos en tiempo real de pago.",
        "url": "https://www.londonstockexchange.com/",
        "reliability": "alta",
        "notes": "Principal bolsa de UK.",
        "verified": True,
    },
    # --- LATAM ---
    {
        "name": "B3 (Bolsa Brasil)",
        "source_type": "bolsa",
        "coverage": "latam",
        "data_offered": "Cotizaciones Bovespa, datos de mercado, derivados",
        "access_type": "web",
        "limitations": "Mayoria de contenido en portugues.",
        "url": "https://www.b3.com.br/",
        "reliability": "alta",
        "notes": "Principal bolsa de Latinoamerica por volumen.",
        "verified": True,
    },
    {
        "name": "Bolsa Mexicana de Valores",
        "source_type": "bolsa",
        "coverage": "latam",
        "data_offered": "Cotizaciones, indices, datos de mercado Mexico",
        "access_type": "web",
        "limitations": "Datos en tiempo real de pago.",
        "url": "https://www.bmv.com.mx/",
        "reliability": "alta",
        "notes": "Bolsa de Mexico. IPC como indice principal.",
        "verified": True,
    },
    {
        "name": "Bolsa de Santiago",
        "source_type": "bolsa",
        "coverage": "latam",
        "data_offered": "Cotizaciones, IPSA, datos de mercado Chile",
        "access_type": "web",
        "limitations": "Cobertura limitada a Chile.",
        "url": "https://www.bolsadesantiago.com/",
        "reliability": "alta",
        "notes": "Bolsa de Chile.",
        "verified": True,
    },
    # --- ASIA ---
    {
        "name": "Japan Exchange Group (JPX/TSE)",
        "source_type": "bolsa",
        "coverage": "asia",
        "data_offered": "Cotizaciones Nikkei, datos de mercado, estadisticas",
        "access_type": "web",
        "limitations": "Contenido principal en japones.",
        "url": "https://www.jpx.co.jp/english/",
        "reliability": "alta",
        "notes": "Bolsa de Tokio. Seccion en ingles disponible.",
        "verified": True,
    },
    {
        "name": "Hong Kong Exchange (HKEX)",
        "source_type": "bolsa",
        "coverage": "asia",
        "data_offered": "Cotizaciones Hang Seng, filings, datos de mercado",
        "access_type": "web",
        "limitations": "Filings en chino/ingles.",
        "url": "https://www.hkex.com.hk/",
        "reliability": "alta",
        "notes": "Bolsa de Hong Kong. Puerta de entrada a mercado chino.",
        "verified": True,
    },
    # --- GLOBAL ---
    {
        "name": "Stooq",
        "source_type": "precios",
        "coverage": "global",
        "data_offered": "Precios historicos acciones, indices, commodities, divisas. Descarga CSV",
        "access_type": "descarga",
        "limitations": "Cobertura variable por mercado. Sin API formal.",
        "url": "https://stooq.com/",
        "reliability": "media",
        "notes": "Buena fuente gratuita de CSV de precios. Cubre muchos mercados.",
        "verified": True,
    },
    {
        "name": "World Bank Open Data",
        "source_type": "macro",
        "coverage": "global",
        "data_offered": "PIB, poblacion, indicadores de desarrollo, comercio internacional",
        "access_type": "web, api",
        "limitations": "Datos macro anuales, no aptos para trading.",
        "url": "https://data.worldbank.org/",
        "reliability": "alta",
        "notes": "Excelente para contexto macro por pais. API REST gratuita.",
        "verified": True,
    },
    {
        "name": "IMF Data",
        "source_type": "macro",
        "coverage": "global",
        "data_offered": "World Economic Outlook, balanza de pagos, deuda publica, estadisticas financieras",
        "access_type": "web, descarga",
        "limitations": "Datos anuales/trimestrales. Publicacion con retraso.",
        "url": "https://www.imf.org/en/Data",
        "reliability": "alta",
        "notes": "Fuente clave para datos macro globales y previsiones.",
        "verified": True,
    },
    {
        "name": "OECD Data",
        "source_type": "macro",
        "coverage": "global",
        "data_offered": "Indicadores economicos, educacion, salud, comercio para paises OCDE",
        "access_type": "web, api",
        "limitations": "Cubre solo paises miembros OCDE principalmente.",
        "url": "https://data.oecd.org/",
        "reliability": "alta",
        "notes": "Datos comparativos entre paises desarrollados. API disponible.",
        "verified": True,
    },
    {
        "name": "BIS Statistics",
        "source_type": "macro",
        "coverage": "global",
        "data_offered": "Estadisticas bancarias internacionales, precios inmobiliarios, credito, tipos de cambio efectivos",
        "access_type": "web, descarga",
        "limitations": "Datos especializados en sector financiero/bancario.",
        "url": "https://www.bis.org/statistics/",
        "reliability": "alta",
        "notes": "Banco de Pagos Internacionales. Datos unicos sobre banca global.",
        "verified": True,
    },
    {
        "name": "Investing.com",
        "source_type": "precios",
        "coverage": "global",
        "data_offered": "Precios, noticias, calendario economico, screener, analisis",
        "access_type": "web",
        "limitations": "Datos con retraso. Scraping no permitido oficialmente.",
        "url": "https://www.investing.com/",
        "reliability": "media",
        "notes": "Buena referencia rapida. Calendario economico muy util. Pendiente de verificacion de TOS para scraping.",
        "verified": True,
    },
]


# ── DATA TAXONOMY ──────────────────────────────────────────────────
DATA_TAXONOMY = {
    "Identificacion": {
        "description": "Datos basicos de la empresa",
        "fields": [
            {"name": "Ticker", "definition": "Simbolo bursatil", "unit": "texto", "periodicity": "estatico"},
            {"name": "ISIN", "definition": "Codigo ISIN internacional", "unit": "texto", "periodicity": "estatico"},
            {"name": "Exchange", "definition": "Bolsa donde cotiza", "unit": "texto", "periodicity": "estatico"},
            {"name": "Pais", "definition": "Pais de domicilio", "unit": "texto", "periodicity": "estatico"},
            {"name": "Moneda", "definition": "Moneda de reporte", "unit": "texto", "periodicity": "estatico"},
            {"name": "Sector", "definition": "Sector GICS o equivalente", "unit": "texto", "periodicity": "estatico"},
            {"name": "Industria", "definition": "Industria especifica", "unit": "texto", "periodicity": "estatico"},
            {"name": "Peers", "definition": "Empresas comparables", "unit": "lista", "periodicity": "variable"},
        ],
    },
    "Income Statement": {
        "description": "Cuenta de resultados",
        "fields": [
            {"name": "Revenue", "definition": "Ingresos totales", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR, CNMV, Yahoo Finance"},
            {"name": "Gross Profit", "definition": "Beneficio bruto = Revenue - COGS", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR, Yahoo Finance"},
            {"name": "Operating Income", "definition": "Resultado operativo (EBIT)", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR, Yahoo Finance"},
            {"name": "Net Income", "definition": "Beneficio neto", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR, Yahoo Finance"},
            {"name": "EPS", "definition": "Beneficio por accion", "unit": "moneda/accion", "periodicity": "trimestral/anual", "sources": "SEC EDGAR, Yahoo Finance"},
            {"name": "Shares Outstanding", "definition": "Acciones en circulacion", "unit": "numero", "periodicity": "trimestral", "sources": "SEC EDGAR, Yahoo Finance"},
        ],
    },
    "Cash Flow": {
        "description": "Estado de flujos de efectivo",
        "fields": [
            {"name": "CFO", "definition": "Cash Flow from Operations", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
            {"name": "Capex", "definition": "Capital Expenditures", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
            {"name": "FCF", "definition": "Free Cash Flow = CFO - Capex", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "Calculado"},
            {"name": "SBC", "definition": "Stock-Based Compensation", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
            {"name": "Dividends Paid", "definition": "Dividendos pagados", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
        ],
    },
    "Balance Sheet": {
        "description": "Balance de situacion",
        "fields": [
            {"name": "Total Assets", "definition": "Activos totales", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
            {"name": "Total Liabilities", "definition": "Pasivos totales", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
            {"name": "Total Equity", "definition": "Patrimonio neto", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
            {"name": "Total Debt", "definition": "Deuda total (corto + largo plazo)", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
            {"name": "Cash & Equivalents", "definition": "Efectivo y equivalentes", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "SEC EDGAR"},
            {"name": "Net Debt", "definition": "Deuda neta = Total Debt - Cash", "unit": "moneda", "periodicity": "trimestral/anual", "sources": "Calculado"},
            {"name": "Current Ratio", "definition": "Activo corriente / Pasivo corriente", "unit": "ratio", "periodicity": "trimestral/anual", "sources": "Calculado"},
        ],
    },
    "Valoracion": {
        "description": "Multiplos y metricas de valoracion",
        "fields": [
            {"name": "Market Cap", "definition": "Capitalizacion bursatil", "unit": "moneda", "periodicity": "diario", "sources": "Yahoo Finance, Stooq"},
            {"name": "Enterprise Value", "definition": "EV = Market Cap + Net Debt - Cash", "unit": "moneda", "periodicity": "diario", "sources": "Calculado"},
            {"name": "P/E", "definition": "Price / Earnings per Share", "unit": "ratio", "periodicity": "diario", "sources": "Yahoo Finance"},
            {"name": "EV/EBITDA", "definition": "Enterprise Value / EBITDA", "unit": "ratio", "periodicity": "trimestral", "sources": "Calculado"},
            {"name": "EV/Sales", "definition": "Enterprise Value / Revenue", "unit": "ratio", "periodicity": "trimestral", "sources": "Calculado"},
            {"name": "P/FCF", "definition": "Price / Free Cash Flow per Share", "unit": "ratio", "periodicity": "trimestral", "sources": "Calculado"},
            {"name": "P/B", "definition": "Price / Book Value per Share", "unit": "ratio", "periodicity": "trimestral", "sources": "Yahoo Finance"},
            {"name": "Dividend Yield", "definition": "Dividendo anual / Precio", "unit": "%", "periodicity": "diario", "sources": "Yahoo Finance"},
        ],
    },
    "DCF Inputs": {
        "description": "Inputs para modelo de flujos descontados (plantilla)",
        "fields": [
            {"name": "Revenue CAGR estimado", "definition": "Tasa de crecimiento compuesto de ingresos", "unit": "%", "periodicity": "anual"},
            {"name": "Terminal Growth", "definition": "Crecimiento perpetuo a largo plazo", "unit": "%", "periodicity": "estatico"},
            {"name": "WACC", "definition": "Coste medio ponderado del capital", "unit": "%", "periodicity": "estatico"},
            {"name": "Target Margin", "definition": "Margen operativo objetivo a largo plazo", "unit": "%", "periodicity": "estatico"},
        ],
    },
    "Riesgo y Cualitativo": {
        "description": "Factores cualitativos y de riesgo",
        "fields": [
            {"name": "Moat", "definition": "Ventaja competitiva sostenible (ninguno/estrecho/amplio)", "unit": "categoria", "periodicity": "variable"},
            {"name": "Concentracion clientes", "definition": "% revenue de top clientes", "unit": "%", "periodicity": "anual"},
            {"name": "Regulacion", "definition": "Nivel de riesgo regulatorio (bajo/medio/alto)", "unit": "categoria", "periodicity": "variable"},
            {"name": "Dependencia commodity", "definition": "Exposicion a precios de materias primas", "unit": "categoria", "periodicity": "variable"},
            {"name": "Riesgo divisa", "definition": "Exposicion a fluctuaciones de tipo de cambio", "unit": "categoria", "periodicity": "variable"},
        ],
    },
    "Eventos": {
        "description": "Eventos corporativos a seguir",
        "fields": [
            {"name": "Earnings date", "definition": "Fecha de publicacion de resultados", "unit": "fecha", "periodicity": "trimestral"},
            {"name": "Guidance", "definition": "Previsiones de la compania", "unit": "texto", "periodicity": "trimestral/anual"},
            {"name": "Ex-Dividend date", "definition": "Fecha ex-dividendo", "unit": "fecha", "periodicity": "variable"},
            {"name": "Buybacks", "definition": "Programas de recompra de acciones", "unit": "moneda", "periodicity": "variable"},
            {"name": "M&A", "definition": "Fusiones y adquisiciones", "unit": "texto", "periodicity": "variable"},
            {"name": "Splits", "definition": "Desdoblamientos de acciones", "unit": "ratio", "periodicity": "variable"},
        ],
    },
}


RATIOS = [
    {
        "name": "Margen Bruto",
        "formula": "Gross Profit / Revenue",
        "definition": "Porcentaje de ingresos que queda tras cubrir el coste de ventas",
        "unit": "%",
        "periodicity": "trimestral/anual",
        "sources": "Calculado a partir de Income Statement",
    },
    {
        "name": "Margen Operativo",
        "formula": "Operating Income / Revenue",
        "definition": "Porcentaje de ingresos que queda tras gastos operativos",
        "unit": "%",
        "periodicity": "trimestral/anual",
        "sources": "Calculado a partir de Income Statement",
    },
    {
        "name": "Margen Neto",
        "formula": "Net Income / Revenue",
        "definition": "Porcentaje de ingresos que queda como beneficio neto",
        "unit": "%",
        "periodicity": "trimestral/anual",
        "sources": "Calculado a partir de Income Statement",
    },
    {
        "name": "ROE (Return on Equity)",
        "formula": "Net Income / Total Equity",
        "definition": "Rentabilidad sobre fondos propios",
        "unit": "%",
        "periodicity": "anual",
        "sources": "Calculado a partir de Income Statement + Balance",
    },
    {
        "name": "ROIC (Return on Invested Capital)",
        "formula": "NOPAT / (Total Equity + Total Debt - Cash)",
        "definition": "Rentabilidad sobre capital invertido. NOPAT = Operating Income * (1 - Tax Rate)",
        "unit": "%",
        "periodicity": "anual",
        "sources": "Calculado a partir de Income Statement + Balance",
    },
    {
        "name": "ROA (Return on Assets)",
        "formula": "Net Income / Total Assets",
        "definition": "Rentabilidad sobre activos totales",
        "unit": "%",
        "periodicity": "anual",
        "sources": "Calculado a partir de Income Statement + Balance",
    },
    {
        "name": "FCF Yield",
        "formula": "FCF / Market Cap",
        "definition": "Rendimiento del flujo de caja libre respecto a capitalizacion",
        "unit": "%",
        "periodicity": "anual",
        "sources": "Calculado a partir de Cash Flow + Market Cap",
    },
    {
        "name": "Deuda/EBITDA",
        "formula": "Total Debt / EBITDA",
        "definition": "Numero de anos de EBITDA necesarios para cubrir la deuda",
        "unit": "x",
        "periodicity": "anual",
        "sources": "Calculado a partir de Balance + Income Statement",
    },
    {
        "name": "Current Ratio",
        "formula": "Current Assets / Current Liabilities",
        "definition": "Capacidad de cubrir pasivos a corto plazo con activos corrientes",
        "unit": "x",
        "periodicity": "trimestral/anual",
        "sources": "Calculado a partir de Balance",
    },
    {
        "name": "EV/EBITDA",
        "formula": "(Market Cap + Net Debt) / EBITDA",
        "definition": "Multiplo de valoracion sobre beneficio operativo bruto",
        "unit": "x",
        "periodicity": "trimestral",
        "sources": "Calculado",
    },
]


def seed_sources(session: Session):
    """Insert seed sources if table is empty."""
    count = session.query(Source).count()
    if count > 0:
        return

    for data in SOURCES_DATA:
        source = Source(
            name=data["name"],
            source_type=data["source_type"],
            coverage=data["coverage"],
            data_offered=data["data_offered"],
            access_type=data["access_type"],
            limitations=data.get("limitations", ""),
            url=data["url"],
            reliability=data.get("reliability", "media"),
            notes=data.get("notes", ""),
            verified=data.get("verified", True),
        )
        session.add(source)

    session.commit()
